<h2>Novo usuário</h2>
<form method="post" action="Request.php?class=UserCtr&method=run&action=new">
<input type="hidden" name="id" id="id">
<label for="name">Nome</label><br>
<input type="text" name="name" id="name" maxlength="50"><br>
<label for="gender">Sexo</label><br>
<select name="gender" id="gender">
    <option value="M">Masculino</option>
    <option value="F">Feminino</option>        
</select><br>
<label for="email">E-mail</label><br>
<input type="email" name="email" id="email"><br>
<label for="password">Senha</label><br>
<input type="password" name="password" id="password"><br> <!-- don't show the password -->

<!-- don't forget confirm if two password fields are equals. 
    Use JS to do it!  -->

<input type="submit" name="command" value="Salvar">
</form>