<h2>Novo usuário</h2>
<form method="post" action="Request.php?class=UserCtr&method=run&action=new">
<input type="hidden" name="id" id="id">
<label for="name">Nome</label><br>
<input type="text" name="name" id="name" maxlength="50"><br>
<label for="gender">Sexo</label><br>
<select name="gender" id="gender">
    <option value="M">Masculino</option>
    <option value="F">Feminino</option>        
</select><br>
<label for="email">E-mail</label><br>
<!-- campo de email -->
<input onblur="verifyEmail(this);" type="email" name="email" id="email">
<!-- loader: mostra um gif de carregamento -->
<img id="loader" src="">

<br>
<label for="password">Senha</label><br>
<input type="password" name="password" id="password"><br> <!-- don't show the password -->

<!-- don't forget confirm if two password fields are equals. 
    Use JS to do it!  -->

<input type="submit" name="command" value="Salvar">
</form>

<script src="core/vendor/jquery-3.4.1.min.js"></script>
<script>
    function verifyEmail(email){        
        $("#loader").attr('src','');
        if(email.value != ''){
            $("#loader").attr('src','core/icon/loading.gif');
            url = "http://localhost/cash_flow/Request.php?class=UserCtr&method=emailExists&email=" + email.value;
            $.getJSON(url, function(data){
                if(data == false)
                    $("#loader").attr('src','core/icon/checked.png');
                else{
                    $("#loader").attr('src','core/icon/warning.png');
                    email.focus();
                }
            });
        }
    }
</script>