
<input type="hidden" name="id" id="id" value="<?=$this->model->getId()?>">
	<label for="name">Nome</label><br>
	<input type="text" name="name" id="name" maxlength="50" value="<?=$this->model->getName()?>"><br>
	<label for="gender">Sexo</label><br>
	<select name="gender" id="gender">
	    <option value="M" <?=$this->model->getGender() == 'M' ? 'selected' : '' ?> >Masculino</option>
	    <option value="F" <?=$this->model->getGender() == 'F' ? 'selected' : '' ?> >Feminino</option>
	        
	</select><br>
	<label for="email">E-mail</label><br>
	<input type="email" name="email" id="email" value="<?=$this->model->getEmail()?>"><br>
	
	<input type="submit" name="command" value="Salvar">
